### ISSUE TITLE
Prevent messages window and exit dialog from opening?

### ISSUE THREAD

**Issue by Shellfishgene** [husonlab/dendroscope3#18]
Hi!

Dendroscope is very nice, and I use it to just quickly check trees also. For that use case the messages window and the exit confirmation dialog are somewhat annoying, can those be turned off somehow?
Also as a quick viewer Dendroscope only works with the workaround described in #4, would be great if doubleclick to open would work right out of the box!

**Comment by husonlab** [comment]
There are command-line options to turn off the splash screen (+s) and the message window (+w) and now also to turn off "confirm quit" (-q), update to release 3.8.2 for the latter feature.

**Comment by Shellfishgene** [comment]
Thanks a lot!
