### ISSUE TITLE
Execute failed because color is null

### ISSUE THREAD

**Issue by RashmiKumari** [husonlab/dendroscope3#21]
Hi,
Dendroscope is an excellent program for phylogenetic tree analysis. I am facing issue with opening nexml and dendro files. Due to this issue, I cannot open formatted tree saved earlier by dendroscope.

I get the following error:
![image](https://user-images.githubusercontent.com/5120257/230396316-a22a1531-1aab-484e-97bb-821764bc986b.png)

I am using 3.8.7 version on Windows.

Thank you very much in advance.

**Comment by husonlab** [comment]
Please update to 3.8.8. see whether this is finally fixed?

**Comment by RashmiKumari** [comment]
Thank you very much for the update. Now, I can open the saved nexml file.
